apiVersion: postgresql.azure.tf.crossplane.io/v1alpha1
kind: PostgresqlConfiguration
metadata:
  name: example
spec:
  forProvider:
    name: array_nulls
    resourceGroupNameRef:
      name: example
    serverNameRef:
      name: example
    value: "off"
  providerConfigRef:
    name: example